services:
  backend:
    build:
      context: ./backend
    container_name: crud-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data.json:/app/data.json

  frontend:
    build:
      context: ./frontend
    container_name: crud-frontend
    ports:
      - "8090:80"
    depends_on:
      - backend
