name: helloworld

on:
  workflow_dispatch:

jobs:
  say_hello_nakama:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/local-hello
        with:
          who-to-greet: "World"
